spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dc-db-dev.cwccnjgib03z.ap-northeast-2.rds.amazonaws.com:3306/DAILY_STUDY_CHECK?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: hoho
    password: algorithm1!
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    org.hibernate.SQL: debug


#spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/DAILY_STUDY_CHECK?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
#    username: hoho_for_jpa_study
#    password: 1234
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: false
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#logging:
#  level:
#    org.hibernate.SQL: debug

---
#spring:
#  profiles:
#    active: "dev"
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://daily-checker-db-instance-1.cwccnjgib03z.ap-northeast-2.rds.amazonaws.com:3306/DAILY_STUDY_CHECK?characterEncoding=UTF-8&serverTimezone=UTC
#    username: hoho
#    password: algorithm1!
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: false
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#logging:
#  level:
#    org.hibernate.SQL: debug